app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class SummonerSearchForm(FlaskForm):
    summoner = StringField('Summoner', validators=[DataRequired(), Length(min=3, max=24)])
    submit = SubmitField('Search')

app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from app.default_conf import Config, init_env

db = SQLAlchemy()
migrate = Migrate()


def create_app(default_configs=Config):
    init_env()
    new_app = Flask(__name__)

    # Load configs
    new_app.config.from_object(default_configs)

    # Init flask extensions
    db.init_app(new_app)
    migrate.init_app(new_app, db)

    # Register Blueprints
    from app.main.routes import bp as main_bp
    new_app.register_blueprint(main_bp)

    return new_app

# Import down here to avoid circular dependency
# import app.flask_models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
import logging
import os

from flask import render_template, redirect, url_for, flash

from app.main import bp
from app.main.forms import SummonerSearchForm
from app.util import RequestHandler
from app.flask_models import *

logger = logging.getLogger(__name__)


@bp.route('/', methods=['GET', 'POST'])
@bp.route("/index", methods=['GET', 'POST'])
def index():
    form = SummonerSearchForm()
    if form.validate_on_submit():
        # flash("Searched for {}".format(form.summoner.data), 'success')
        return redirect(url_for('main.search_name', summoner_name=form.summoner.data))
    return render_template('index.html', form=form)


@bp.route('/summoner/name/<summoner_name>', methods=['GET', 'POST'])
def search_name(summoner_name):
    form = SummonerSearchForm()
    if form.validate_on_submit():
        # flash("Searched for {}".format(form.summoner.data), 'success')
        return redirect(url_for('main.search_name', summoner_name=form.summoner.data))
    rh = RequestHandler(db, api_endpoint=os.environ.get('API_ENDPOINT'), api_key=os.environ.get('API_KEY'))
    # For now we will update all summoner information on search
    retrieved_sum = rh.insert_or_update_summoner(summoner_name)
    if not retrieved_sum:
        flash("Error getting Summoner from API, returning info stored in the DB")
        retrieved_sum = rh.get_summoner_by_name(summoner_name)
    if not retrieved_sum:
        logger.warning("Could not get summoner object for {}".format(summoner_name))
        return render_template('summoner.html', form=form)
    rh.update_recent_usermatches(retrieved_sum.accountid)
    rh.update_leagues(retrieved_sum.id)
    updated_sum = rh.get_summoner_by_id(retrieved_sum.id)
    return render_template('summoner.html', summoner=updated_sum, form=form)


@bp.route("/test", methods=['GET', 'POST'])
def test():
    form = SummonerSearchForm()
    if form.validate_on_submit():
        # flash("Searched for {}".format(form.summoner.data), 'success')
        return redirect(url_for('main.search_name', summoner_name=form.summoner.data))
    logger.info(os.environ.get('API_ENDPOINT'))
    logger.info(os.environ.get('API_KEY'))
    rh = RequestHandler(db, api_endpoint=os.environ.get('API_ENDPOINT'), api_key=os.environ.get('API_KEY'))
    sums = rh.get_all_summoners()
    matches = rh.get_all_db_usermatches()
    leagues = rh.get_all_userleagues()
    return render_template('test.html', summoners=sums, matches=matches, leagues=leagues, form=form)

app/util/__init__.py
from app.util.request_handler import RequestHandler

app/wrappers/__init__.py
from app.wrappers.riot_request import RiotConnector

app/templates/base-navbar.html
{% extends "base.html" %}
{% block body %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('main.index') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('main.test') }}">Test</a>
            </li>
            <!--
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            -->
        </ul>
        <form class="form-inline my-2 my-lg-0" method="POST" action="">
            {{ form.hidden_tag() }}
            {{ form.summoner(class="form-control mr-sm-2", placeholder="Summoner Search") }}
            <!-- <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search"> -->
            {{ form.submit(class="btn btn-outline-success my-2 my-sm-0") }}
            <!-- <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
        </form>
    </div>
</nav>
{% block main %}{% endblock main %}
{% endblock body %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous" />
    <!-- custom CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/main.css') }}" />
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Riot API Webapp</title>
    {% endif %}
    {% block head %}{% endblock head %}
</head>
<body>
{% block body %}{% endblock body %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
</body>
</html>

app/templates/home.html
{% extends "base-navbar.html" %}
{% block main %}
<main role="main" class="container">

    <div class="starter-template">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for cat, msg in messages %}
                    <div class="alert alert-{{ cat }}">
                        {{ msg }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% if form.summoner.errors %}
            <div class="alert alert-danger">
                {% for error in form.summoner.errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
        <h1>Home Page</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a
            mostly barebones HTML document.</p>
        {% for summoner in summoners %}
        <p class="lead">{{ summoner }}</p>
        {% endfor %}
        <table class="lead">
            <tr>
                <th>id</th>
                <th>gameid</th>
                <th>champion</th>
            </tr>
            {% for match in usermatches %}
            <tr>
                <td>{{ match.id }}</td>
                <td>{{ match.gameid }}</td>
                <td>{{ match.champion }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>

</main><!-- /.container -->
{% endblock main %}

app/templates/index.html
{% extends "base-navbar.html" %}
{% block main %}
<main role="main" class="container">

    <div class="starter-template">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for cat, msg in messages %}
                    <div class="alert alert-{{ cat }}">
                        {{ msg }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% if form.summoner.errors %}
            <div class="alert alert-danger">
                {% for error in form.summoner.errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
        <h1>Home Page</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a
            mostly barebones HTML document.</p>
    </div>

</main><!-- /.container -->
{% endblock main %}

app/templates/summoner.html
{% extends "base-navbar.html" %}
{% block main %}
<main role="main" class="container">
    <div class="starter-template">
        <h1>{{ summoner.name }}</h1>
        <table class="lead">
            <tr>
                <th>name</th>
                <th>date_time</th>
                <th>gameid</th>
                <th>champion</th>
            </tr>
            {% for match in summoner.matches %}
            <tr>
                <td>{{ summoner.name }}</td>
                <td>{{ match.timestamp }}</td>
                <td>{{ match.gameid }}</td>
                <td>{{ match.champion }}</td>
            </tr>
            {% endfor %}
        </table>
        {% if summoner.leagues %}
            {% for league in summoner.leagues %}
                <p class="lead">{{ league }}</p>
            {% endfor %}
        {% endif %}
    </div>
</main><!-- /.container -->
{% endblock main %}

app/templates/test.html
{% extends "base-navbar.html" %}
{% block main %}
<main role="main" class="container">

    <div class="starter-template">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for cat, msg in messages %}
                    <div class="alert alert-{{ cat }}">
                        {{ msg }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% if form.summoner.errors %}
            <div class="alert alert-danger">
                {% for error in form.summoner.errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
        <h1>Test Page</h1>
        {% for summoner in summoners %}
            <p class="lead">{{ summoner }}</p>
        {% endfor %}
        {% if matches %}
        <table class="lead">
            <tr>
                <th>Summoner</th>
                <th>gameid</th>
                <th>champion</th>
                <th>season</th>
            </tr>
            {% for match in matches %}
            <tr>
                <td>{{ match.summoner.name }}</td>
                <td>{{ match.gameid }}</td>
                <td>{{ match.champion }}</td>
                <td>{{ match.season }}</td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
        {% if leagues %}
            {% for league in leagues %}
                <p class="lead">{{ league }}</p>
            {% endfor %}
        {% endif %}
    </div>

</main><!-- /.container -->
{% endblock main %}